import { type Material } from "./materialsApi";

export const MATERIALS_MOCK: { materials: Material[] } = {
  materials: [
    {
      id: 1,
      title: "Кирпич строительный рядовой полнотелый красный",
      description: "250×120×65 мм",
      image: "",
      consumption: 0.03,
      count: 512,
      mainMaterial: "Керамика",
      countPerM2: 62,
      countPerM3: 512,
      netWeight: 3.67,
      lengthMM: 250,
      heightMM: 65,
      widthMM: 120,
      country: "Россия",
    },
    {
      id: 2,
      title: "Блок газобетонный",
      description: "600×250×100 мм",
      image: "",
      consumption: 0.05,
      count: 67,
      mainMaterial: "Газобетон",
      countPerM2: 12,
      countPerM3: 67,
      netWeight: 2.5,
      lengthMM: 600,
      heightMM: 100,
      widthMM: 250,
      country: "Россия",
    },
    {
      id: 3,
      title: "Блок керамический",
      description: "250×219×510 мм",
      image: "",
      consumption: 0.04,
      count: 36,
      mainMaterial: "Керамика",
      countPerM2: 15,
      countPerM3: 36,
      netWeight: 4.2,
      lengthMM: 250,
      heightMM: 510,
      widthMM: 219,
      country: "Россия",
    },
    {
      id: 4,
      title: "Кирпич строительный силикатный полнотелый белый",
      description: "250×120×65 мм",
      image: "",
      consumption: 0.5,
      count: 512,
      mainMaterial: "Силикат",
      countPerM2: 60,
      countPerM3: 512,
      netWeight: 3.9,
      lengthMM: 250,
      heightMM: 65,
      widthMM: 120,
      country: "Россия",
    },
    {
      id: 5,
      title: "Кирпич шамотный огнеупорный",
      description: "230×114×65 мм",
      image: "",
      consumption: 0.035,
      count: 587,
      mainMaterial: "Шамот",
      countPerM2: 55,
      countPerM3: 587,
      netWeight: 3.5,
      lengthMM: 230,
      heightMM: 65,
      widthMM: 114,
      country: "Россия",
    },
    {
      id: 6,
      title: "Кирпич фасадный клинкерный пустотелый красный гладкий",
      description: "250×120×65 мм",
      image: "",
      consumption: 0.03,
      count: 513,
      mainMaterial: "Клинкер",
      countPerM2: 63,
      countPerM3: 513,
      netWeight: 3.8,
      lengthMM: 250,
      heightMM: 65,
      widthMM: 120,
      country: "Германия",
    },
    {
      id: 7,
      title: "Блок керамзитобетонный пустотелый Стандарт Керамзит",
      description: "390×190×188 мм",
      image: "",
      consumption: 0.02,
      count: 72,
      mainMaterial: "Керамзитобетон",
      countPerM2: 14,
      countPerM3: 72,
      netWeight: 5.1,
      lengthMM: 390,
      heightMM: 188,
      widthMM: 190,
      country: "Россия",
    },
  ],
};
